# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alain Pellaux - Développeur web à Genève
email: contact@alainpellaux.me
description: > # this means to ignore newlines until "baseurl:"
  Alain Pellaux, je suis un développeur de sites et d'applications web, spécialisé PHP à Genève, en Suisse.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alain.info" # the base hostname & protocol for your site
twitter_username: gallib_net
github_username:  gallib

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude: ["node_modules", "gulpfile.js", "package.json"]